name = "Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bed014228cc220a23f0cc08a0b4f16ea80a11158abd568b4209694fb563970f5"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
